# Generated by Django 4.2.7 on 2023-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=99)),
                ("timestamp", models.DateTimeField()),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("url", models.CharField(max_length=99)),
                ("human_count", models.IntegerField()),
                ("human_mode", models.CharField(max_length=9)),
                ("reviewed", models.BooleanField()),
            ],
        ),
    ]
