# Generated by Django 4.2.7 on 2023-11-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="id",
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="timestamp",
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
