# Generated by Django 4.2.7 on 2023-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_remove_screenshot_id_alter_screenshot_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshot",
            name="human_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="human_mode",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="reviewed",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="url",
            field=models.CharField(max_length=99, null=True),
        ),
    ]
